version: v2
plugins:
  - local:
      [
        "go",
        "tool",
        "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2",
      ]
    out: artifacts/docs
    opt:
      - logtostderr=true
      - openapi_naming_strategy=fqn
      - json_names_for_fields=false
      - generate_unbound_methods=true
      - allow_merge=true
      - merge_file_name=openapi
